# Generated by Django 4.2.1 on 2023-05-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table_comment': 'Product',
            },
        ),
    ]
